#!/bin/bash
#
# pi - Pharo Install - A MIT-pip-like library for Pharo Smalltalk
#
# Listing supports SmalltalkHub and GitHub.
# 	SmalltalkHub listing requires libxml2 (xmllint command)
#	GitHub listing requires jq command (it will be downloaded if not present)
# Installs currently supported for:
# 	Metacello Configurations from Catalog (command line handler: get)
# 	SmalltalkHub (command line handler: config)
#
# It works with curl or wget
# Tested on Windows 8.1, MacOS, GNU/Linux

#set -x

#################################
## Main Section
#################################

setDownloadApp
parseCmdLine $1
